### Register a new user
POST http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
  "login": "newuser",
  "password": "SenHa123",
  "name": "Jonas Pereira",
  "email": "mock@gmail.com",
  "role": "ADMIN"
}