CREATE TABLE devotionals
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    content         VARCHAR(3000),
    date            date,
    bible_verses_id BIGINT,
    CONSTRAINT pk_devotionals PRIMARY KEY (id)
);

ALTER TABLE devotionals
    ADD CONSTRAINT FK_DEVOTIONALS_ON_BIBLE_VERSES FOREIGN KEY (bible_verses_id) REFERENCES bible_verses (id);